config/routes.rb
Rails.application.routes.draw do
  resources :user_streams, only: [:show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :stream
  belongs_to :user
end

app/models/stream.rb
class Stream < ApplicationRecord
  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_streams
  has_many :streams, through: :user_streams
  has_many :messages
end

app/models/user_stream.rb
class UserStream < ApplicationRecord
  belongs_to :user
  belongs_to :stream
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_streams_controller.rb
class UserStreamsController < ApplicationController
  def show
    @streams = Stream.all
    @user = User.first
    @stream_messages = @user.streams.joins(:messages).uniq.flat_map(&:messages)
  end

  def create
    @user = User.first
    stream = Stream.find(params[:stream_id])
    user_stream = UserStream.create(user: @user, stream: stream)

    redirect_to user_stream_path(user_stream)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="4.0.0";
    analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    analytics.page();
    }}();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_pack_tag :application %>

<%= yield :javascript %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "flashes" -%>
  <div class="container-fluid">
    <%= yield %>
  </div>
  <%= render "javascript" %>
  <%= render "css_overrides" %>
</body>
</html>

app/views/messages/_message.html.erb
<div class="row border-bottom p-1">
  <div class="col col-lg-2">
    <p># <%= message.stream.name %></p>
    <p><strong><%= message.user.display_name%></strong></p>
    <p><small><%= message.created_at.strftime("%D %T") %></small></p>
  </div>
  <div class="col-8">
    <p class="lead"><%= message.body %></p>
  </div>
</div>

app/views/user_streams/show.html.erb
<div class="row">
  <div class="col col-lg-2 side-panel p-0 bg-light bg-gradient">
    <ul class="list-group">
    <li class="list-group-item"><%=@user.display_name%></li>
    <li class="list-group-item disabled">Chat options</li>
    <% @streams.all.map do |stream| %>
      <li class="list-group-item">
        <%= stream.name %>
        <%= link_to '+', user_streams_path(stream_id: stream), class: "btn btn-primary stretched-link", id: "#{stream.id}", method: :post%>
      </li>
    <% end %>


    </ul>
  </div>
  <div class="col stream">
    <%= render partial: 'messages/message', collection: @stream_messages %>
  </div>
</div>